apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse
      sources:
        direct: false
        stages:
          - test
  promotionTemplate:
    spec:
      vars:
        - name: openPr
          value: "true"
      steps:
        - task:
            name: promotion
