apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse
      sources:
        direct: false
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promotion
